add_executable(console console.cpp)
target_link_libraries(console PRIVATE loom-core)

add_executable(window window.cpp)
add_executable(widget widget.cpp)
add_executable(nested_windows nested_windows.cpp)

if(APPLE)
    target_link_libraries(window        PRIVATE loom-core    "-framework Cocoa")
    target_link_libraries(widget        PRIVATE loom-widgets "-framework Cocoa")
    target_link_libraries(nested_windows PRIVATE loom-widgets "-framework Cocoa")
else()
    target_link_libraries(window        PRIVATE loom-core)
    target_link_libraries(widget        PRIVATE loom-widgets)
    target_link_libraries(nested_windows PRIVATE loom-widgets)
endif()
