cmake_minimum_required(VERSION 3.25)

set(_LOOM_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

unset(LOOM_WEB_DIR CACHE)
if(NOT DEFINED LOOM_WEB_DIR)
    set(LOOM_WEB_DIR "${CMAKE_CURRENT_LIST_DIR}/../src/core/src/platform/web")
endif()

function(loom_add_executable target)
    set(_sources ${ARGN})

    if(CMAKE_SYSTEM_NAME STREQUAL "WASI")
        add_executable(${target} ${_sources} "${_LOOM_WEB_INIT_SRC}")
        target_link_libraries(${target} PRIVATE loom-widgets)
        set_target_properties(${target} PROPERTIES
            OUTPUT_NAME "loom_app"
            SUFFIX      ".wasm"
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${target}"
        )

        add_custom_command(TARGET ${target} PRE_LINK
            COMMAND ${CMAKE_COMMAND} -E remove -f
                "${CMAKE_CURRENT_BINARY_DIR}/${target}/loom_app.wasm"
            COMMENT "Removing stale ${target}/loom_app.wasm before link"
        )

        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND}
                -DWASM_FILE="$<TARGET_FILE:${target}>"
                -P "${_LOOM_CMAKE_DIR}/SyncWasm.cmake"
            COMMENT "Flushing ${target}/loom_app.wasm to disk"
        )

        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND}
                -DWASM_FILE="$<TARGET_FILE:${target}>"
                -P "${_LOOM_CMAKE_DIR}/CheckWasm.cmake"
            COMMENT "Verifying WASM magic bytes in $<TARGET_FILE_NAME:${target}>"
        )

        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${LOOM_WEB_DIR}/index.html"
                "$<TARGET_FILE_DIR:${target}>/index.html"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${LOOM_WEB_DIR}/loom.js"
                "$<TARGET_FILE_DIR:${target}>/loom.js"
            COMMENT "Copying web assets → $<TARGET_FILE_DIR:${target}>"
        )

        if(LOOM_GALLERY_DIR)
            add_custom_command(TARGET ${target} POST_BUILD
                COMMAND ${CMAKE_COMMAND} -E copy_directory
                    "$<TARGET_FILE_DIR:${target}>"
                    "${LOOM_GALLERY_DIR}/examples/${target}"
                COMMENT "Gallery: syncing ${target}"
            )
        endif()

    else()
        add_executable(${target} ${_sources} "${_LOOM_NATIVE_MAIN_SRC}")
        target_link_libraries(${target} PRIVATE loom-widgets)
    endif()
endfunction()

function(loom_add_gallery gallery_target)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "EXAMPLES")

    if(NOT CMAKE_SYSTEM_NAME STREQUAL "WASI")
        return()
    endif()

    if(NOT ARG_EXAMPLES)
        message(FATAL_ERROR "loom_add_gallery: EXAMPLES list is empty")
    endif()

    set(_gallery_dir "${CMAKE_BINARY_DIR}/gallery")

    set(_js_items "")
    foreach(_ex IN LISTS ARG_EXAMPLES)
        string(REGEX REPLACE "^loom_" "" _label "${_ex}")
        string(REPLACE "_" " " _label "${_label}")
        if(_js_items)
            string(APPEND _js_items ",\n      ")
        endif()
        string(APPEND _js_items
            "{ id: '${_ex}', label: '${_label}', path: 'examples/${_ex}' }")
    endforeach()

    set(GALLERY_EXAMPLES "${_js_items}")
    configure_file(
        "${LOOM_WEB_DIR}/gallery.html"
        "${_gallery_dir}/index.html"
        @ONLY
    )

    set(LOOM_GALLERY_DIR "${_gallery_dir}" CACHE INTERNAL
        "Output directory for the active gallery target")

    set(_LOOM_GALLERY_TARGET   "${gallery_target}"  CACHE INTERNAL "")
    set(_LOOM_GALLERY_EXAMPLES "${ARG_EXAMPLES}"    CACHE INTERNAL "")

    message(STATUS "Loom gallery '${gallery_target}' → ${_gallery_dir}")
endfunction()

function(loom_gallery_finish)
    if(NOT _LOOM_GALLERY_TARGET)
        return()
    endif()
    add_custom_target(${_LOOM_GALLERY_TARGET} ALL)
    add_dependencies(${_LOOM_GALLERY_TARGET} ${_LOOM_GALLERY_EXAMPLES})
endfunction()

if(CMAKE_SYSTEM_NAME STREQUAL "WASI")
    set(_LOOM_WEB_INIT_SRC "${CMAKE_BINARY_DIR}/_loom_web_init.cpp")
    file(CONFIGURE OUTPUT "${_LOOM_WEB_INIT_SRC}" CONTENT
"// Auto-generated by LoomHelpers.cmake — do not edit.\n\
//\n\
// wasm-ld synthesises __wasm_call_ctors as the aggregated C++ global-constructor\n\
// runner.  In the WASI reactor model it is never placed in the WASM start section\n\
// and the host (loom.js) calls loom_init() directly — bypassing _start — so we\n\
// must invoke __wasm_call_ctors() ourselves before entering user code.\n\
extern \"C\" void __wasm_call_ctors();\n\
extern int loom_main(int argc, char *argv[]);\n\
static int s_argc = 0;\n\
static char *s_argv[1] = {nullptr};\n\
extern \"C\"\n\
__attribute__((export_name(\"loom_init\")))\n\
void loom_init() { __wasm_call_ctors(); loom_main(s_argc, s_argv); }\n"
    )
else()
    set(_LOOM_NATIVE_MAIN_SRC "${CMAKE_BINARY_DIR}/_loom_native_main.cpp")
    file(CONFIGURE OUTPUT "${_LOOM_NATIVE_MAIN_SRC}" CONTENT
"// Auto-generated by LoomHelpers.cmake — do not edit.\n\
extern int loom_main(int argc, char *argv[]);\n\
int main(int argc, char *argv[]) { return loom_main(argc, argv); }\n"
    )
endif()
